## Encoding Categorical label

### Recap

In [41]:


#Supress warnings
import warnings
warnings.filterwarnings('ignore')

# Importing the libraries
import numpy as np
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [42]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

### Encoding to integers using Label Encoder

In [43]:
#Encode the country and purchased variables
from sklearn.preprocessing import LabelEncoder
help(LabelEncoder)

Help on class LabelEncoder in module sklearn.preprocessing.label:

class LabelEncoder(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
 |  Encode labels with value between 0 and n_classes-1.
 |  
 |  Read more in the :ref:`User Guide <preprocessing_targets>`.
 |  
 |  Attributes
 |  ----------
 |  classes_ : array of shape (n_class,)
 |      Holds the label for each class.
 |  
 |  Examples
 |  --------
 |  `LabelEncoder` can be used to normalize labels.
 |  
 |  >>> from sklearn import preprocessing
 |  >>> le = preprocessing.LabelEncoder()
 |  >>> le.fit([1, 2, 2, 6])
 |  LabelEncoder()
 |  >>> le.classes_
 |  array([1, 2, 6])
 |  >>> le.transform([1, 1, 2, 6]) #doctest: +ELLIPSIS
 |  array([0, 0, 1, 2]...)
 |  >>> le.inverse_transform([0, 0, 1, 2])
 |  array([1, 1, 2, 6])
 |  
 |  It can also be used to transform non-numerical labels (as long as they are
 |  hashable and comparable) to numerical labels.
 |  
 |  >>> le = preprocessing.LabelEncoder()
 |  >>> le.fit(["paris"

In [44]:
le_X = LabelEncoder() #create obj 

In [45]:
le_X.fit_transform(X[:,0]) #you can also use fit_transform menthod for imputer

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [46]:
X[:,0] = le_X.fit_transform(X[:,0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

#### However, this is not desirable as ML model thinks one country could be better than other. So we need 01 encodings

In [48]:
#for 01 encoding
from sklearn.preprocessing import OneHotEncoder
help(OneHotEncoder)

Help on class OneHotEncoder in module sklearn.preprocessing.data:

class OneHotEncoder(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
 |  Encode categorical integer features using a one-hot aka one-of-K scheme.
 |  
 |  The input to this transformer should be a matrix of integers, denoting
 |  the values taken on by categorical (discrete) features. The output will be
 |  a sparse matrix where each column corresponds to one possible value of one
 |  feature. It is assumed that input features take on values in the range
 |  [0, n_values).
 |  
 |  This encoding is needed for feeding categorical data to many scikit-learn
 |  estimators, notably linear models and SVMs with the standard kernels.
 |  
 |  Note: a one-hot encoding of y labels should use a LabelBinarizer
 |  instead.
 |  
 |  Read more in the :ref:`User Guide <preprocessing_categorical_features>`.
 |  
 |  Parameters
 |  ----------
 |  n_values : 'auto', int or array of ints
 |      Number of values per feature.
 |

In [49]:
oe = OneHotEncoder(categorical_features=[0])#specify index of column that has categorical variable

In [50]:
X = oe.fit_transform(X).toarray()

In [51]:
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True) #Otherwise prints in scientific format
print(X)

[[    1.         0.         0.        44.     72000.    ]
 [    0.         0.         1.        27.     48000.    ]
 [    0.         1.         0.        30.     54000.    ]
 [    0.         0.         1.        38.     61000.    ]
 [    0.         1.         0.        40.     63777.7778]
 [    1.         0.         0.        35.     58000.    ]
 [    0.         0.         1.        38.7778 52000.    ]
 [    1.         0.         0.        48.     79000.    ]
 [    0.         1.         0.        50.     83000.    ]
 [    1.         0.         0.        37.     67000.    ]]


In [52]:
#Similarly do for label encoder. For dep variable, we only need label encoder (01 for binary classification)
le_y = LabelEncoder()

In [53]:
y = le_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])