## Understanding tf.placeholders

In [13]:
import tensorflow as tf

#### x becomes the parameter for y

In [15]:
x = tf.placeholder("float", None)
y = x * 2

In [16]:
y

<tf.Tensor 'mul_2:0' shape=<unknown> dtype=float32>

#### Type and Dimension of x need not necessarily be known beforehand

In [23]:
X = 3
with tf.Session() as session:
    o = session.run(y,feed_dict={x:X})
    print(o)

6.0


In [24]:
X = [1,2,3]
with tf.Session() as session:
    o = session.run(y,feed_dict={x:X})
    print(o)

[2. 4. 6.]


In [28]:
import numpy as np

X = np.ones((5,5))
with tf.Session() as session:
    o = session.run(y,feed_dict={x:X})
    print(o)

[[8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]]


In [26]:
x = tf.placeholder(tf.float32, [None, None])
z= x*2
y = z*4

In [27]:
X = np.ones((5,5))
with tf.Session() as session:
    o = session.run(y,feed_dict={x:X})
    print(o)

[[8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]]


In [33]:
X = np.ones((5,5))
X.shape

(5, 5)

In [35]:
X[None,:].shape

(1, 5, 5)

#### Implementing matrix multiplication that accepts an input X

In [53]:
W1 = np.random.rand(10,5)
B1 = np.random.rand(1,5)
def lrelu(x, leak=0.2):
    f1 = 0.5 * (1 + leak)
    f2 = 0.5 * (1 - leak)
    return f1 * x + f2 * abs(x)

In [54]:
X = np.ones((1,10))
Y = tf.matmul(X,W1) + B1
Y = lrelu(Y)
print(Y)
with tf.Session() as session:
    o = session.run(Y)
    print(o)

Tensor("add_4:0", shape=(1, 5), dtype=float64)
[[6.67493998 5.83188298 7.59696945 4.77142672 6.06864424]]
